---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${SC_WORDPRESS}
parameters:
  volBackendFs: vol01
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
